### ISSUE TITLE
Sort out licensing with Krepa

### ISSUE THREAD

**Issue by ProMcTagonist** [ProMcTagonist/smilies#1]
@krepa098 

Did you license raw.svg? Is it GPLv3 because it's in the qTox repo?

**Comment by krepa098** [comment]
> Is it GPLv3 because it's in the qTox repo?

Yes. It seems like the Apache license and the GPLv3 are somehow compatible so you're probably not in need of a license change?

**Comment by ProMcTagonist** [comment]
Okay. So the cat bits can go into the normal ones (which I've done) but it can't go the other way around. Cat bits are apache, everything else is GPLv3. Thanks.

Now I've got to figure out how to apply two different licenses to different files in a folder.
