### ISSUE TITLE
Sort out licensing with qTox

### ISSUE THREAD

**Issue by ProMcTagonist** [ProMcTagonist/smilies#2]
Goals:
- Comply with apache for the cat ones, pick a good license for them all, and have a pack that's potentially usable in qTox

@tux3

**Comment by tux3** [comment]
I don't care much for licenses as long as they are reasonnably free, but you'll probably want to be on the safe side. Apache seems to work okay with GPLv3 so it's fine by me.

**Comment by ProMcTagonist** [comment]
Alright, thanks.
